// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wrcpbmqmkeuvgweyvpqo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndyY3BibXFta2V1dmd3ZXl2cHFvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxMzIxMzcsImV4cCI6MjA2MjcwODEzN30.wopfhV1IbWlTCQbLmOPup6Kp8ekTUIZOm7qVrz1wYEw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);